version: '3.4'

services:
  crawler:
    image: ${DOCKER_REGISTRY-}crawler
    container_name: crawler
    ports:
      - 5000:5000
    depends_on:
      - postgresDb
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - crawler-network


  postgresDb:
    image: postgres
    container_name: postgresDb
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docker -d crawler_db"]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
      PGDATA: /data/postgres
      POSTGRES_DB: crawler_db
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - crawler-network
  
networks:
  crawler-network:
    name: crawler-network

volumes:
  db-data: